# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LanguageBug
email: gob.bueno AT gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thesis project. MA in Digital Media Design for Learning at NYU.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://guibueno.github.io" # the base hostname & protocol for your site
tagline: "Portuguese"
twitter_username: gobbueno2
github_username:  guibueno

# Build settings
markdown: kramdown

# Plug-ins
extlinks:
  attributes: {rel: nofollow, target: _blank}

# Gui's new features
collections:
#  principles:
#      output: true
  docs:
      output: true
  people:
      output: true
  deadlines:
      output: true
  meetings:
      output: true
  logs:
      output: true
  weeks:
      output: true
  indies:
      output: true
  landscapeaudit:
      output: true
  faq:
      output: true
  languagebug:
      output: true
  exercises:
      output: true
  principles:
      output: true
  rationale:
      output: true
  features:
      output: true
  sections:
      output: true