# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LanguageBug
# email: gob.bueno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Language learning software to teach novice spoken Portuguese.
  MA in Digital Media Design for Learning at NYU thesis project.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://guibueno.github.io" # the base hostname & protocol for your site
twitter_username: gobbueno2
github_username:  guibueno

# Build settings
markdown: kramdown
